logging:
  level: "INFO"
  filename: ""
redis:
  host: "localhost"
  port: 6379
device:
  name: "four_motor_driver"
  options:
    motors:
      front_left:
        direction_pin: 17
        speed_pin: 27
        reverse: 0
      front_right:
        direction_pin: 3
        speed_pin: 4
        reverse: 0
      rear_left:
        direction_pin: 5
        speed_pin: 6
        reverse: 0
      rear_right:
        direction_pin: 7
        speed_pin: 8
        reverse: 0
